### ISSUE TITLE
Unhandled binding: PackageBinding on package Javadoc references

### ISSUE THREAD

**Issue by SquidDev** [CadixDev/Mercury#41]
Attempting to remap [CC: Restitched](https://github.com/Merith-TK/cc-restitched) throws the following exception:

<details>
<summary>Stack trace</summary>

```
java.lang.RuntimeException: Failed to process: /home/squid/cc-restitched/src/main/java/dan200/computercraft/shared/network/NetworkMessage.java
        at org.cadixdev.mercury.Mercury.accept(Mercury.java:237)
        at org.cadixdev.mercury.Mercury$Requestor.acceptAST(Mercury.java:260)
        at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:1068)
        at org.eclipse.jdt.core.dom.CompilationUnitResolver.resolve(CompilationUnitResolver.java:662)
        at org.eclipse.jdt.core.dom.ASTParser.createASTs(ASTParser.java:1013)
        at org.cadixdev.mercury.Mercury.run(Mercury.java:212)
        at org.cadixdev.mercury.Mercury.rewrite(Mercury.java:167)
        at net.fabricmc.loom.task.MigrateMappingsTask.migrateMappings(MigrateMappingsTask.java:189)
        ...
Caused by: java.lang.IllegalStateException: Unhandled binding: PackageBinding (1)
        at org.cadixdev.mercury.remapper.RemapperVisitor.visit(RemapperVisitor.java:189)
        at org.cadixdev.mercury.remapper.SimpleRemapperVisitor.visit(SimpleRemapperVisitor.java:183)
        at org.eclipse.jdt.core.dom.SimpleName.accept0(SimpleName.java:198)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2975)
        at org.eclipse.jdt.core.dom.QualifiedName.accept0(QualifiedName.java:162)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2975)
        at org.eclipse.jdt.core.dom.QualifiedName.accept0(QualifiedName.java:162)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2975)
        at org.eclipse.jdt.core.dom.QualifiedName.accept0(QualifiedName.java:162)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2975)
        at org.eclipse.jdt.core.dom.QualifiedName.accept0(QualifiedName.java:162)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2998)
        at org.eclipse.jdt.core.dom.TagElement.accept0(TagElement.java:317)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2998)
        at org.eclipse.jdt.core.dom.Javadoc.accept0(Javadoc.java:194)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChild(ASTNode.java:2975)
        at org.eclipse.jdt.core.dom.TypeDeclaration.accept0(TypeDeclaration.java:441)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2998)
        at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:258)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2927)
        at org.cadixdev.mercury.remapper.MercuryRemapper.rewrite(MercuryRemapper.java:54)
        at org.cadixdev.mercury.SourceRewriter.process(SourceRewriter.java:20)
        at org.cadixdev.mercury.SourceContext.process(SourceContext.java:82)
        at org.cadixdev.mercury.RewriteContext.process(RewriteContext.java:106)
        at org.cadixdev.mercury.Mercury.accept(Mercury.java:235)
        ... 136 more
```

</details>

Looking [at the file in question](https://github.com/Merith-TK/cc-restitched/blob/fabric/src/main/java/dan200/computercraft/shared/network/NetworkMessage.java), I believe this is caused by the `@see` references to Java packages.

I assume a suitable bodge would be to just add a `break;` after this comment (so it's skipped, rather than throwing an exception), but there may better solutions

https://github.com/CadixDev/Mercury/blob/409123d3e9737a0349753b8d197bde126020f8b6/src/main/java/org/cadixdev/mercury/remapper/RemapperVisitor.java#L190-L192

**Comment by jamierocks** [comment]
This was fixed by https://github.com/CadixDev/Mercury/commit/7fa0ba1e03bec3facd084e3d69102a2f6e7afa17 :)

**Comment by SquidDev** [comment]
Oh, sorry! I searched the issue tracker for `PackageBinding`, but didn't try other search terms.

Thank you for the impossibly speedy fix! :)

**Comment by jamierocks** [comment]
I'm not sure if it's a dependency you can update in your environment, but I made a note to release a new version today following this conversation - [0.1.0](https://github.com/CadixDev/Mercury/releases/tag/0.1.0) :)
